on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main
jobs:
  web-bff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: web-bff  
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install flake8 black   # Install linters and formatters

      - name: Run Linting (flake8)
        working-directory: web-bff  
        run: |
          source venv/bin/activate
          flake8 . --count --show-source --statistics

      - name: Check Code Formatting (black)
        working-directory: web-bff  
        run: |
          source venv/bin/activate
          black --check .    

      - name: Run FastAPI app
        working-directory: web-bff  
        run: |
          source venv/bin/activate
          uvicorn main:app --host 127.0.0.1 --port 8000 &

      - name: Check if service is running
        run: curl -f http://127.0.0.1:8000/