on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main
jobs:
  web-bff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run web-bff container
        run: |
          docker build -t web-bff -f docker/web-bff.Dockerfile .
          docker run -d -p 8000:8000 web-bff
          sleep 10  # Wait for container to start

      - name: Run tests
        run: |
          CONTAINER_ID=$(docker ps -q)
          docker exec $CONTAINER_ID mise exec -- poetry run pytest --asyncio-mode=auto tests/

      - name: Check if service is running
        run: curl -f http://localhost:8000/